/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bff/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardSummaryEnvelope"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders (BFF) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPageEnvelope"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Create order (BFF) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderBffRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOrderEnvelope"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order (BFF) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderEnvelope"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/order-detail/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order detail aggregate (BFF) */
        get: {
            parameters: {
                query?: {
                    includePayment?: boolean;
                    includeShipment?: boolean;
                    includeReservations?: boolean;
                };
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderDetailEnvelope"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create checkout flow (BFF) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCheckoutBffRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCheckoutEnvelope"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get relationship graph (BFF) */
        get: {
            parameters: {
                query: {
                    rootType: "USER" | "ORDER" | "SHIPMENT" | "PAYMENT";
                    rootId: string;
                    depth?: number;
                    maxEvents?: number;
                    maxNodes?: number;
                    includeEvents?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphEnvelope"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bff/system-concepts/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system concepts bootstrap data (BFF) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemConceptsBootstrapEnvelope"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            success: boolean;
        };
        ErrorEnvelope: components["schemas"]["SuccessEnvelope"] & {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        OrderItem: {
            sku: string;
            quantity: number;
        };
        Order: {
            orderId: string;
            userId: string;
            status: string;
            amount: number;
            currency: string;
            items: components["schemas"]["OrderItem"][];
            paymentId: string | null;
        };
        CreateOrderBffRequest: {
            /** Format: uuid */
            userId: string;
            amount: number;
            currency: string;
            items?: components["schemas"]["OrderItem"][];
        };
        CreateOrderResponse: {
            orderId: string;
        };
        Money: {
            currency: string;
            amountMinor: number;
        };
        InventoryItem: {
            itemId: string;
            sku: string;
            price: components["schemas"]["Money"];
            availableQuantity: number;
            reservedQuantity: number;
        };
        InventoryReservation: {
            reservationId: string;
            orderId: string;
            sku: string;
            quantity: number;
        };
        PaymentIntent: {
            paymentId: string;
            orderId: string;
            amount: number;
            currency: string;
            status: string;
        };
        ScheduledPaymentEvent: {
            eventType: string;
            delaySeconds: number;
            outboxId: string;
        };
        CreatePaymentIntentResponse: {
            paymentId: string;
            status: string;
            scheduled: components["schemas"]["ScheduledPaymentEvent"];
        };
        Shipment: {
            shipmentId: string;
            orderId: string;
            status: string;
        };
        UserProfile: {
            userId: string;
            displayName: string;
            /** Format: email */
            email: string;
            avatarId?: string;
            avatarUrl?: string;
        };
        OrderDetail: {
            order: components["schemas"]["Order"];
            paymentIntent: components["schemas"]["PaymentIntent"];
            shipment: components["schemas"]["Shipment"];
            reservations: components["schemas"]["InventoryReservation"][];
            partialErrors?: string[];
        };
        DashboardSummary: {
            orders: components["schemas"]["Order"][];
            paymentIntents: components["schemas"]["PaymentIntent"][];
            shipments: components["schemas"]["Shipment"][];
            inventoryItems: components["schemas"]["InventoryItem"][];
            partialErrors?: string[];
        };
        CreateCheckoutBffRequest: {
            /** Format: uuid */
            userId: string;
            amount: number;
            currency: string;
            items?: components["schemas"]["OrderItem"][];
            /** @enum {string} */
            simulateOutcome?: "SUCCEEDED" | "FAILED";
            simulateDelaySeconds?: number;
        };
        CreateCheckoutResponse: {
            orderId: string;
            payment: components["schemas"]["CreatePaymentIntentResponse"];
        };
        GraphNode: {
            id: string;
            type: string;
            label: string;
            data?: {
                [key: string]: unknown;
            };
        };
        GraphEdge: {
            id: string;
            from: string;
            to: string;
            type: string;
            label?: string;
        };
        Graph: {
            rootNodeId: string;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
            truncated?: boolean;
        };
        PaginatedOrder: {
            items: components["schemas"]["Order"][];
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
        };
        PaginatedUserProfile: {
            items: components["schemas"]["UserProfile"][];
            offset: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
        };
        PaginatedInventoryItem: {
            items: components["schemas"]["InventoryItem"][];
            offset: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
        };
        SystemConceptsBootstrap: {
            users: components["schemas"]["PaginatedUserProfile"];
            inventoryItems: components["schemas"]["PaginatedInventoryItem"];
        };
        DashboardSummaryEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["DashboardSummary"];
        };
        OrderPageEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["PaginatedOrder"];
        };
        CreateOrderEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["CreateOrderResponse"];
        };
        OrderEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["Order"];
        };
        OrderDetailEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["OrderDetail"];
        };
        CreateCheckoutEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["CreateCheckoutResponse"];
        };
        GraphEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["Graph"];
        };
        SystemConceptsBootstrapEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data: components["schemas"]["SystemConceptsBootstrap"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
