name: clean-ddd-ci

on:
    pull_request:
    push:
        branches: [main]

permissions:
    contents: read

jobs:
    backend:
        uses: ./.github/workflows/reusable-node-ci-task.yml
        with:
            run_script: |
                pnpm --version
                pnpm --filter api lint
                pnpm --filter api typecheck
                pnpm --filter api build
                pnpm --filter api test

    frontend:
        uses: ./.github/workflows/reusable-node-ci-task.yml
        with:
            run_script: |
                pnpm --filter admin lint
                pnpm --filter admin typecheck
                pnpm --filter admin build
                pnpm --filter admin test
